name: Deploy to Hatchbox.io
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to Hatchbox.io
        uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
